### ISSUE TITLE
the "remoteuser@" is lost on Re-add Closed Sessions

### ISSUE THREAD

**Issue by harridu** [duncs/clusterssh#76] opened 2017-03-02 07:42 UTC
If I run cssh using `cssh remoteuser1@host1 remoteuser2@host2`, close the window for host1, and finally select Hosts --> Re-add closed sessions, then the "remoteuser1@" has been omitted for the new connection. I get a password dialog for a bad account name for host1.

**Comment by duncs** [comment] 2017-03-03 22:59
closed as appears to be a duplicate of #72

**Closed by duncs** 2017-03-03 22:59 UTC
